In [1]:
import pandas as pd

labels_df = pd.read_csv("../../data/Verified_dataset/labels/labels_merged.csv")

/var/folders/j5/prvccmy93sn3187zg4qcc1_40000gn/T/ipykernel_33172/3776020851.py:3: DtypeWarning: Columns (0: boat_labeling_file) have mixed types. Specify dtype option on import or set low_memory=False.
  labels_df = pd.read_csv("../../data/Verified_dataset/labels/labels_merged.csv")

In [24]:
labels_df.columns

Index(['clip_filename', 'ECHO', 'BBPC', 'HFPC', 'Whistle', 'Call', 'Boat',
       'labeling_effort', 'DETAIL', 'Begin Time (s)', 'End Time (s)',
       'GROUNDTRUTH', 'Notes', 'original_filename', 'labeled_snippet_filename',
       'snippet_start_time', 'snippet_start_s', 'snippet_end_s', 'Site',
       'labeled_snippet_dir', 'HydrophoneModel', 'HydrophoneSensitivity',
       'clip_start_time', 'clip_end_time', 'DETAILS', 'boat_labeling_file',
       'boat_labeling_file_id', 'annotator', 'SnippetFilename', 'start_s',
       'end_s', 'FIXED_GROUNDTRUTH'],
      dtype='str')

In [6]:
labels_df["Boat"] = labels_df["Boat"].fillna(0)

In [19]:
def get_calls_table(labels_df, group_col="Site"):

    call_types = ["HFPC", "BBPC", "ECHO", "Whistle"]

    call_counts = labels_df.groupby(group_col)["Call"].value_counts().unstack(fill_value=0)
    call_counts = call_counts.rename(columns={1: "Present", 0: "Absent"})[["Present", "Absent"]]

    call_type_counts = labels_df.groupby(group_col)[call_types].sum().astype(int)

    table = pd.concat([call_counts, call_type_counts], axis=1)
    table.loc["Total"] = table.sum()
    table = table.astype(int)
    return table

In [20]:
get_calls_table(labels_df)

       Present  Absent  HFPC  BBPC  ECHO  Whistle
Site
BSM       1198    7161   293   193  1021      338
CAC       2159    1608   179   318  1321     1630
KAM       2983    1082   177   327  2819      646
RDL        514     436   157   221   223      333
Total     6854   10287   806  1059  5384     2947

In [21]:
get_calls_table(labels_df, "Boat")

       Present  Absent  HFPC  BBPC  ECHO  Whistle
Boat
0.0       3833    7330   577   818  2628     2547
1.0       3021    2957   229   241  2756      400
Total     6854   10287   806  1059  5384     2947

In [27]:
boat_only = labels_df.groupby("labeled_snippet_filename").filter(lambda g: (g["Boat"] == 1).all())
boat_only.groupby("labeled_snippet_filename")["BBPC"].sum().sort_values(ascending=False).head(10)

labeled_snippet_filename
6871.220821133604.snippet.wav         68
201359382.210714083053.snippet.wav    36
5725.200801150830.snippet.wav         22
5725.200726191905.snippet.wav         19
5725.200726195504.snippet.wav         18
5725.200731142245.snippet.wav         14
5725.200731140339.snippet.wav          8
6871.220829131406.snippet.wav          6
5725.200801152155.snippet.wav          6
5725.200730132804.snippet.wav          4
Name: BBPC, dtype: int64

In [ ]:
labels_df[labels_df["labeled_snippet_filename"] == "5725.200801150830.snippet.wav"]["BBPC"].value_counts()
labels_df[labels_df["labeled_snippet_filename"] == "5725.200801150830.snippet.wav"]["HFPC"].value_counts()

In [28]:
boat_only = labels_df.groupby("labeled_snippet_filename").filter(lambda g: (g["Boat"] == 1).all())
boat_only.groupby("labeled_snippet_filename")["HFPC"].sum().sort_values(ascending=False).head(10)

labeled_snippet_filename
201359382.170724133858.snippet.wav    45
201359382.210714083053.snippet.wav    44
5725.200731140339.snippet.wav         21
5725.200730132804.snippet.wav         10
6871.220821133604.snippet.wav          9
5725.200726191905.snippet.wav          9
5725.200730132426.snippet.wav          7
5725.200731141523.snippet.wav          7
6871.220829131406.snippet.wav          3
5725.200801152155.snippet.wav          3
Name: HFPC, dtype: int64