# Model optimization results analysis

### This file handles the results of the model optimization results done in `run_experiments.ipynb`, and generates the table seen in the paper

In [9]:
from dotenv import load_dotenv
from pathlib import Path
import sys
import os

# Walk up until we find the project root (folder with the .env)
current_path = Path().resolve()
for parent in [current_path] + list(current_path.parents):
    if (parent / ".env").exists():
        load_dotenv(parent / ".env")
        project_root = os.getenv("PROJECT_ROOT")
        print(project_root)
        sys.path.append(project_root)     
        break


%load_ext autoreload
%autoreload 2

C:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
from sklearn.metrics import f1_score
import numpy as np
import json
import pandas as pd
import os
import matplotlib.pyplot as plt
from training.utils import calculate_detection_f1

pd.set_option('display.max_columns', None) 
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [11]:
from models.utils import aggregate_folds_testing_metrics


# results_dir = "../results/model_optimization"  
results_dir = "../new_results/optimization"  
runs = [d for d in os.listdir(results_dir) if os.path.isdir(os.path.join(results_dir, d))]
runs

# Load cross validation results for each run
cross_val_results = {}
for run in runs:

    aggregate_folds_testing_metrics(f"{results_dir}/{run}")
    res_obj = {}
    results_path = os.path.join(results_dir, run, "cross_val_test_results.json")
    if os.path.exists(results_path):
        with open(results_path, 'r') as f:
            res_obj["test_results"] = json.load(f)

    if os.path.exists(os.path.join(results_dir, run, "test_predictions.csv")):
        res_obj["test_predictions_df"] = pd.read_csv(os.path.join(results_dir, run, "test_predictions.csv"))
        cross_val_results[run] = res_obj

In [12]:
def create_metrics_df(cross_val_results, round_to=2):
    # Define the metrics and categories we want to track
    metrics = ['f1', 'precision', 'recall', 'accuracy']
    categories = ['Labels_Average', 'ECHO', 'HFPC', "BBPC", 'Whistle']
    
    # Initialize list to store all metrics
    metrics_list = []
    for run, res_obj in cross_val_results.items():
        print()
        test_results = res_obj["test_results"]
        test_predictions_df = res_obj["test_predictions_df"]

        # Calculate detection F1
        detection_f1 = calculate_detection_f1(test_predictions_df)
        print(detection_f1)
        # Process main results
        main_metric_row = {
            'run': run,
            'test_type': 'fp32',
            # 'detection_f1': round(detection_f1["mean"], round_to),
            # 'detection_f1_std': round(detection_f1["std"], round_to),
            'model_size_mb': round(test_results['model_info']['model_size_mb'],2) if test_results['model_info'] and test_results['model_info']['model_size_mb'] is not None else None,
            'model_size_kb': round(test_results['model_info']['model_size_kb']) if test_results['model_info'] and test_results['model_info']['model_size_kb'] is not None else None,
        }
        
        # Add main results metrics
        for metric in metrics:
            for category in categories:
                base_name = f"{category}_{metric}" if category != 'Labels_Average' else metric
                main_metric_row[base_name] = round(test_results['main_results'][metric][category]['mean'], round_to)
                main_metric_row[f"{base_name}_std"] = round(test_results['main_results'][metric][category]['std'], round_to)
        
        metrics_list.append(main_metric_row)
        
        # Process other tests
        for test_name, test_metrics in test_results['other_tests'].items():
            other_metric_row = {
                'run': run,
                'test_type': test_name,
                # 'detection_f1': round(detection_f1["mean"], 3),  # Keep the same detection F1
                # 'detection_f1_std': round(detection_f1["std"], 3)
            }
            if test_name == "quantized":
                other_metric_row['model_size_mb'] = round(test_results['model_info']['quantized_model_size_mb'],2)
                other_metric_row['model_size_kb'] = round(test_results['model_info']['quantized_model_size_kb'])
            
            # Add other test metrics
            for metric in metrics:
                for category in categories:
                    base_name = f"{category}_{metric}" if category != 'Labels_Average' else metric
                    other_metric_row[base_name] = round(test_metrics[metric][category]['mean'], round_to)
                    other_metric_row[f"{base_name}_std"] = round(test_metrics[metric][category]['std'], round_to)
            
            metrics_list.append(other_metric_row)
    
    # Create DataFrame
    df = pd.DataFrame(metrics_list)
    
    # Reorder columns to have run and test_type first
    cols = df.columns.tolist()
    cols.remove('run')
    cols.remove('test_type')
    df = df[['run', 'test_type',] + cols]
    
    return df

metrics_df = create_metrics_df(cross_val_results, round_to=2)

0.8633661961516633

0.8579804174258248

0.8313770743287381

0.8122272403704192

0.8353686778213005

In [15]:
metrics_df["test_type"].value_counts()

test_type
fp32                  5
Site_KAM              5
Site_CAC              5
Site_RDL              5
Site_BSM              5
Boat_1.0              5
Boat_0.0              5
quantized             2
Site_KAM_quantized    2
Site_CAC_quantized    2
Site_RDL_quantized    2
Site_BSM_quantized    2
Boat_1.0_quantized    2
Boat_0.0_quantized    2
Name: count, dtype: int64

In [18]:
# metrics_df = metrics_df[metrics_df["run"].str.contains("qat|resnet")]

f1_columns = ['run', 'test_type', 'model_size_mb', 'model_size_kb']  +[col for col in metrics_df.columns if 'f1' in col.lower() and 'std' not in col.lower()]
accuracy_columns = ['run', 'test_type', 'model_size_mb', 'model_size_kb']  +[col for col in metrics_df.columns if 'accuracy' in col.lower()]

# Display metrics with only f1-related columns
metrics_df[metrics_df["test_type"].isin(["fp32", "quantized"])][f1_columns]

,run,test_type,model_size_mb,model_size_kb,f1,ECHO_f1,HFPC_f1,BBPC_f1,Whistle_f1
0,mobile_net_12_layers,fp32,4.42,4321.0,0.87,0.92,0.85,0.81,0.87
7,mobile_net_8_layers,fp32,0.89,866.0,0.85,0.92,0.84,0.79,0.86
14,mobile_net_qat_12_layers,fp32,4.96,4847.0,0.86,0.92,0.84,0.81,0.86
15,mobile_net_qat_12_layers,quantized,1.36,1328.0,0.85,0.92,0.84,0.79,0.86
28,mobile_net_qat_8_layers,fp32,1.22,1188.0,0.85,0.91,0.82,0.80,0.87
29,mobile_net_qat_8_layers,quantized,0.35,343.0,0.84,0.91,0.82,0.78,0.87
42,resnet,fp32,45.28,44223.0,0.85,0.92,0.85,0.79,0.85

In [20]:
metrics_df[metrics_df["test_type"].isin(["fp32", "Boat_0.0", "Boat_1.0", "Boat_0.0_quantized", "Boat_1.0_quantized"])][f1_columns]

,run,test_type,model_size_mb,model_size_kb,f1,ECHO_f1,HFPC_f1,BBPC_f1,Whistle_f1
0,mobile_net_12_layers,fp32,4.42,4321.0,0.87,0.92,0.85,0.81,0.87
5,mobile_net_12_layers,Boat_1.0,NaN,NaN,0.76,0.94,0.80,0.63,0.68
6,mobile_net_12_layers,Boat_0.0,NaN,NaN,0.88,0.89,0.88,0.85,0.90
7,mobile_net_8_layers,fp32,0.89,866.0,0.85,0.92,0.84,0.79,0.86
12,mobile_net_8_layers,Boat_1.0,NaN,NaN,0.75,0.94,0.79,0.61,0.66
13,mobile_net_8_layers,Boat_0.0,NaN,NaN,0.86,0.88,0.86,0.84,0.88
14,mobile_net_qat_12_layers,fp32,4.96,4847.0,0.86,0.92,0.84,0.81,0.86
24,mobile_net_qat_12_layers,Boat_1.0,NaN,NaN,0.75,0.94,0.81,0.65,0.61
25,mobile_net_qat_12_layers,Boat_1.0_quantized,NaN,NaN,0.74,0.94,0.80,0.62,0.61
26,mobile_net_qat_12_layers,Boat_0.0,NaN,NaN,0.87,0.88,0.86,0.84,0.90
27,mobile_net_qat_12_layers,Boat_0.0_quantized,NaN,NaN,0.86,0.88,0.86,0.83,0.89
28,mobile_net_qat_8_layers,fp32,1.22,1188.0,0.85,0.91,0.82,0.80,0.87
38,mobile_net_qat_8_layers,Boat_1.0,NaN,NaN,0.76,0.92,0.76,0.65,0.69
39,mobile_net_qat_8_layers,Boat_1.0_quantized,NaN,NaN,0.74,0.92,0.78,0.61,0.66
40,mobile_net_qat_8_layers,Boat_0.0,NaN,NaN,0.86,0.85,0.86,0.84,0.90
41,mobile_net_qat_8_layers,Boat_0.0_quantized,NaN,NaN,0.86,0.85,0.85,0.83,0.90
42,resnet,fp32,45.28,44223.0,0.85,0.92,0.85,0.79,0.85
47,resnet,Boat_1.0,NaN,NaN,0.76,0.90,0.81,0.66,0.67
48,resnet,Boat_0.0,NaN,NaN,0.87,0.90,0.88,0.84,0.88

In [ ]:
metrics_df[~metrics_df['run'].str.contains('000', na=False)][f1_columns].sort_values('f1', ascending=False)
metrics_df[~metrics_df['run'].str.contains('000', na=False)][accuracy_columns].sort_values('accuracy', ascending=False)