# Model optimization results analysis

### This file handles the results of the model optimization results done in `run_experiments.ipynb`, and generates the table seen in the paper

In [27]:
from dotenv import load_dotenv
from pathlib import Path
import sys
import os

# Walk up until we find the project root (folder with the .env)
current_path = Path().resolve()
for parent in [current_path] + list(current_path.parents):
    if (parent / ".env").exists():
        load_dotenv(parent / ".env")
        project_root = os.getenv("PROJECT_ROOT")
        print(project_root)
        sys.path.append(project_root)     
        break


%load_ext autoreload
%autoreload 2

C:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [28]:
from sklearn.metrics import f1_score
import numpy as np
import json
import pandas as pd
import os
import matplotlib.pyplot as plt
from training.utils import calculate_detection_f1

pd.set_option('display.max_columns', None) 
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [29]:
from models.utils import aggregate_folds_testing_metrics


# results_dir = "../results/model_optimization"  
results_dir = "../final_results"  
runs = [d for d in os.listdir(results_dir) if os.path.isdir(os.path.join(results_dir, d))]
runs

# Load cross validation results for each run
cross_val_results = {}
for run in runs:

    aggregate_folds_testing_metrics(f"{results_dir}/{run}")
    res_obj = {}
    results_path = os.path.join(results_dir, run, "cross_val_test_results.json")
    if os.path.exists(results_path):
        with open(results_path, 'r') as f:
            res_obj["test_results"] = json.load(f)

    if os.path.exists(os.path.join(results_dir, run, "test_predictions.csv")):
        res_obj["test_predictions_df"] = pd.read_csv(os.path.join(results_dir, run, "test_predictions.csv"))
        cross_val_results[run] = res_obj

In [30]:
def create_metrics_df(cross_val_results, round_to=2):
    # Define the metrics and categories we want to track
    metrics = ['f1', 'precision', 'recall', 'accuracy']
    categories = ['Labels_Average', 'ECHO', 'HFPC', "BBPC", 'Whistle']
    
    # Initialize list to store all metrics
    metrics_list = []
    for run, res_obj in cross_val_results.items():
        print()
        test_results = res_obj["test_results"]
        test_predictions_df = res_obj["test_predictions_df"]

        # Calculate detection F1
        detection_f1 = calculate_detection_f1(test_predictions_df)
        print(detection_f1)
        # Process main results
        main_metric_row = {
            'run': run,
            'test_type': 'fp32',
            # 'detection_f1': round(detection_f1["mean"], round_to),
            # 'detection_f1_std': round(detection_f1["std"], round_to),
            'model_size_mb': round(test_results['model_info']['model_size_mb'],2) if test_results['model_info'] and test_results['model_info']['model_size_mb'] is not None else None,
            'model_size_kb': round(test_results['model_info']['model_size_kb']) if test_results['model_info'] and test_results['model_info']['model_size_kb'] is not None else None,
        }
        
        # Add main results metrics
        for metric in metrics:
            for category in categories:
                base_name = f"{category}_{metric}" if category != 'Labels_Average' else metric
                main_metric_row[base_name] = round(test_results['main_results'][metric][category]['mean'], round_to)
                main_metric_row[f"{base_name}_std"] = round(test_results['main_results'][metric][category]['std'], round_to)
        
        metrics_list.append(main_metric_row)
        
        # Process other tests
        for test_name, test_metrics in test_results['other_tests'].items():
            other_metric_row = {
                'run': run,
                'test_type': test_name,
                # 'detection_f1': round(detection_f1["mean"], 3),  # Keep the same detection F1
                # 'detection_f1_std': round(detection_f1["std"], 3)
            }
            if test_name == "quantized":
                other_metric_row['model_size_mb'] = round(test_results['model_info']['quantized_model_size_mb'],2)
                other_metric_row['model_size_kb'] = round(test_results['model_info']['quantized_model_size_kb'])
            
            # Add other test metrics
            for metric in metrics:
                for category in categories:
                    base_name = f"{category}_{metric}" if category != 'Labels_Average' else metric
                    other_metric_row[base_name] = round(test_metrics[metric][category]['mean'], round_to)
                    other_metric_row[f"{base_name}_std"] = round(test_metrics[metric][category]['std'], round_to)
            
            metrics_list.append(other_metric_row)
    
    # Create DataFrame
    df = pd.DataFrame(metrics_list)
    
    # Reorder columns to have run and test_type first
    cols = df.columns.tolist()
    cols.remove('run')
    cols.remove('test_type')
    df = df[['run', 'test_type',] + cols]
    
    return df

metrics_df = create_metrics_df(cross_val_results, round_to=2)

0.9362878439168985

0.9328035623457804

0.9274793013717041

0.9351307196191329

0.9387965782224156

0.9325718693203031

0.93375197226733

0.9323905689588321

0.930686031127917

In [31]:
metrics_df

,run,test_type,model_size_mb,model_size_kb,f1,f1_std,ECHO_f1,ECHO_f1_std,HFPC_f1,HFPC_f1_std,BBPC_f1,BBPC_f1_std,Whistle_f1,Whistle_f1_std,precision,precision_std,ECHO_precision,ECHO_precision_std,HFPC_precision,HFPC_precision_std,BBPC_precision,BBPC_precision_std,Whistle_precision,Whistle_precision_std,recall,recall_std,ECHO_recall,ECHO_recall_std,HFPC_recall,HFPC_recall_std,BBPC_recall,BBPC_recall_std,Whistle_recall,Whistle_recall_std,accuracy,accuracy_std,ECHO_accuracy,ECHO_accuracy_std,HFPC_accuracy,HFPC_accuracy_std,BBPC_accuracy,BBPC_accuracy_std,Whistle_accuracy,Whistle_accuracy_std
0,mobile_net_10_layers,fp32,2.51,2449.0,0.89,0.01,0.94,0.01,0.87,0.01,0.84,0.02,0.90,0.01,0.89,0.02,0.94,0.02,0.87,0.03,0.87,0.04,0.89,0.02,0.88,0.01,0.93,0.01,0.87,0.03,0.82,0.01,0.91,0.02,0.97,0.00,0.96,0.01,0.99,0.00,0.98,0.00,0.96,0.00
1,mobile_net_10_layers,KAM,NaN,NaN,0.86,0.02,0.96,0.00,0.80,0.02,0.83,0.03,0.87,0.03,0.88,0.02,0.96,0.01,0.82,0.07,0.87,0.06,0.86,0.03,0.85,0.03,0.95,0.01,0.79,0.06,0.79,0.03,0.88,0.04,0.96,0.00,0.94,0.00,0.98,0.00,0.97,0.01,0.95,0.01
2,mobile_net_10_layers,BSM,NaN,NaN,0.87,0.01,0.92,0.02,0.88,0.02,0.85,0.02,0.86,0.03,0.87,0.02,0.91,0.03,0.87,0.04,0.86,0.02,0.82,0.04,0.89,0.01,0.92,0.01,0.89,0.02,0.84,0.03,0.90,0.04,0.99,0.00,0.98,0.01,0.99,0.00,0.99,0.00,0.99,0.00
3,mobile_net_10_layers,RDL,NaN,NaN,0.89,0.01,0.84,0.04,0.93,0.03,0.84,0.04,0.95,0.02,0.89,0.02,0.84,0.08,0.91,0.04,0.85,0.04,0.96,0.03,0.90,0.01,0.85,0.02,0.95,0.04,0.84,0.06,0.95,0.02,0.94,0.01,0.92,0.03,0.97,0.01,0.93,0.02,0.96,0.02
4,mobile_net_10_layers,CAC,NaN,NaN,0.89,0.01,0.92,0.01,0.86,0.04,0.86,0.04,0.91,0.02,0.91,0.02,0.95,0.03,0.89,0.08,0.88,0.05,0.91,0.03,0.88,0.01,0.90,0.02,0.85,0.07,0.84,0.06,0.91,0.02,0.95,0.01,0.94,0.01,0.99,0.00,0.97,0.01,0.91,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,resnet,fp32,45.28,44223.0,0.88,0.01,0.94,0.00,0.86,0.01,0.82,0.02,0.89,0.01,0.89,0.01,0.94,0.01,0.86,0.03,0.85,0.02,0.89,0.02,0.86,0.01,0.93,0.00,0.86,0.02,0.78,0.01,0.89,0.01,0.97,0.00,0.96,0.00,0.99,0.00,0.98,0.00,0.96,0.00
61,resnet,RDL,NaN,NaN,0.87,0.01,0.82,0.05,0.90,0.03,0.84,0.06,0.94,0.02,0.87,0.02,0.81,0.07,0.85,0.03,0.85,0.09,0.96,0.02,0.88,0.02,0.83,0.05,0.94,0.04,0.83,0.05,0.93,0.03,0.93,0.01,0.90,0.03,0.95,0.01,0.93,0.03,0.95,0.02
62,resnet,KAM,NaN,NaN,0.86,0.01,0.96,0.00,0.80,0.03,0.82,0.02,0.86,0.02,0.88,0.03,0.96,0.00,0.83,0.06,0.87,0.05,0.88,0.05,0.84,0.01,0.96,0.01,0.77,0.03,0.78,0.02,0.85,0.03,0.96,0.00,0.94,0.01,0.98,0.00,0.97,0.00,0.95,0.01
63,resnet,BSM,NaN,NaN,0.85,0.01,0.91,0.02,0.87,0.01,0.78,0.05,0.84,0.03,0.85,0.01,0.91,0.03,0.86,0.04,0.84,0.06,0.81,0.02,0.85,0.01,0.91,0.02,0.88,0.05,0.74,0.06,0.88,0.05,0.99,0.00,0.98,0.01,0.99,0.00,0.99,0.00,0.99,0.00
64,resnet,CAC,NaN,NaN,0.88,0.01,0.92,0.00,0.87,0.03,0.82,0.04,0.90,0.01,0.90,0.02,0.95,0.02,0.88,0.08,0.85,0.07,0.91,0.01,0.86,0.02,0.90,0.01,0.86,0.03,0.80,0.05,0.90,0.01,0.95,0.00,0.94,0.00,0.99,0.00,0.97,0.01,0.90,0.01

In [32]:
# metrics_df = metrics_df[metrics_df["run"].str.contains("qat|resnet")]

f1_columns = ['run', 'test_type', 'model_size_mb', 'model_size_kb']  +[col for col in metrics_df.columns if 'f1' in col.lower()]
accuracy_columns = ['run', 'test_type', 'model_size_mb', 'model_size_kb']  +[col for col in metrics_df.columns if 'accuracy' in col.lower()]

# Display metrics with only f1-related columns
metrics_df[metrics_df["test_type"].isin(["fp32", "quantized"])][f1_columns]

,run,test_type,model_size_mb,model_size_kb,f1,f1_std,ECHO_f1,ECHO_f1_std,HFPC_f1,HFPC_f1_std,BBPC_f1,BBPC_f1_std,Whistle_f1,Whistle_f1_std
0,mobile_net_10_layers,fp32,2.51,2449.0,0.89,0.01,0.94,0.01,0.87,0.01,0.84,0.02,0.90,0.01
5,mobile_net_12_layers,fp32,4.42,4321.0,0.88,0.01,0.94,0.00,0.85,0.01,0.84,0.03,0.90,0.01
10,mobile_net_6_layers,fp32,0.65,637.0,0.87,0.01,0.93,0.01,0.84,0.02,0.82,0.02,0.89,0.01
15,mobile_net_8_layers,fp32,0.89,866.0,0.87,0.01,0.94,0.00,0.84,0.01,0.83,0.02,0.89,0.01
20,mobile_net_qat_10_layers,fp32,2.96,2892.0,0.88,0.01,0.94,0.00,0.83,0.02,0.84,0.01,0.90,0.01
21,mobile_net_qat_10_layers,quantized,0.83,807.0,0.87,0.01,0.93,0.01,0.84,0.02,0.83,0.02,0.90,0.01
30,mobile_net_qat_12_layers,fp32,4.96,4847.0,0.87,0.01,0.94,0.01,0.85,0.01,0.82,0.02,0.89,0.01
31,mobile_net_qat_12_layers,quantized,1.36,1328.0,0.87,0.01,0.93,0.01,0.85,0.02,0.81,0.03,0.89,0.01
40,mobile_net_qat_6_layers,fp32,0.89,871.0,0.87,0.01,0.94,0.00,0.83,0.02,0.80,0.01,0.89,0.01
41,mobile_net_qat_6_layers,quantized,0.26,252.0,0.86,0.00,0.94,0.00,0.83,0.03,0.80,0.01,0.89,0.01
50,mobile_net_qat_8_layers,fp32,1.22,1188.0,0.88,0.01,0.94,0.00,0.84,0.02,0.83,0.02,0.90,0.01
51,mobile_net_qat_8_layers,quantized,0.35,343.0,0.87,0.01,0.93,0.00,0.83,0.03,0.83,0.01,0.90,0.01
60,resnet,fp32,45.28,44223.0,0.88,0.01,0.94,0.00,0.86,0.01,0.82,0.02,0.89,0.01

In [ ]:
metrics_df[~metrics_df['run'].str.contains('000', na=False)][f1_columns].sort_values('f1', ascending=False)
metrics_df[~metrics_df['run'].str.contains('000', na=False)][accuracy_columns].sort_values('accuracy', ascending=False)